language: node_js
node_js:
  - "14.5"
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
script:
  - nohup npm run start &
  - sleep 3
  - npm run test

  # nohup         - If shell is closed, don't kill anything created by this command
  # npm run start - Runs the server
  # &             - Run this command in a subshell (in the background)
  # sleep 3       - Wait 3 seconds. Gives us time to startup the server
